# Read about factories at https://github.com/thoughtbot/factory_girl

FactoryGirl.define do
  factory :company_layout do
    company_id 1
    header_background_color "MyString"
    home_background_color "MyString"
    what_i_do_background_color "MyString"
    who_i_am_background_color "MyString"
    album_background_color "MyString"
    my_work_background_color "MyString"
    contact_us_background_color "MyString"
    footer_background_color "MyString"
    header_font_color "MyString"
    home_name_font_color "MyString"
    home_description_font_color "MyString"
    what_i_do_name_font_color "MyString"
    what_i_do_description_font_color "MyString"
    who_i_am_name_font_color "MyString"
    who_i_am_description_font_color "MyString"
    album_name_font_color "MyString"
    album_description_font_color "MyString"
    my_work_name_font_color "MyString"
    my_work_description_font_color "MyString"
    contact_us_name_font_color "MyString"
    contact_us_description_font_color "MyString"
    footer_font_color "MyString"
    header_font "MyString"
    home_name_font "MyString"
    home_description_font "MyString"
    what_i_do_name_font "MyString"
    what_i_do_description_font "MyString"
    who_i_am_name_font "MyString"
    who_i_am_description_font "MyString"
    album_name_font "MyString"
    album_description_font "MyString"
    my_work_name_font "MyString"
    my_work_description_font "MyString"
    contact_us_name_font "MyString"
    contact_us_description_font "MyString"
    footer_font "MyString"
    header_font_size "MyString"
    home_name_font_size "MyString"
    home_description_font_size "MyString"
    what_i_do_name_font_size "MyString"
    what_i_do_description_font_size "MyString"
    who_i_am_name_font_size "MyString"
    who_i_am_description_font_size "MyString"
    album_name_font_size "MyString"
    album_description_font_size "MyString"
    my_work_name_font_size "MyString"
    my_work_description_font_size "MyString"
    contact_us_name_font_size "MyString"
    contact_us_description_font_size "MyString"
    footer_font_size "MyString"
  end
end
